import {
  createCipheriv,
  createDecipheriv,
  createHash,
  randomBytes,
} from "node:crypto";
import { createReadStream, createWriteStream } from "node:fs";
import { open, stat } from "node:fs/promises";
import { pipeline } from "node:stream/promises";

export const savedAppPackage = "flyhub-saved-apps";
export const savedAppVersion = "1";
export const appNamePattern = /^flyhub-app-[a-z0-9-]+-[a-f0-9]{12}$/;
export const savedIdPattern = /^[a-f0-9]{32}$/;
export type SavedApp = {
  id: string;
  name: string;
  sourceApp: string;
  createdAt: string;
  imageRef: string;
  sizeBytes?: number;
};

export function savedImageRef(user: string, id: string): string {
  if (!/^[a-z0-9][a-z0-9-]{0,38}$/i.test(user) || !savedIdPattern.test(id))
    throw new Error("Invalid saved app reference.");
  return `ghcr.io/${user.toLowerCase()}/${savedAppPackage}:app-${id}`;
}

export function savedAppFromManifest(
  manifest: {
    annotations?: Record<string, string>;
    layers?: Array<{ size?: number }>;
  },
  user: string,
  tag: string,
): SavedApp | null {
  const id = tag.replace(/^app-/, "");
  const a = manifest.annotations ?? {};
  if (
    !savedIdPattern.test(id) ||
    a["app.flyhub.version"] !== savedAppVersion ||
    !appNamePattern.test(a["app.flyhub.source"] ?? "")
  )
    return null;
  return {
    id,
    name: (a["org.opencontainers.image.title"] ?? "Saved app").slice(0, 80),
    sourceApp: a["app.flyhub.source"]!,
    createdAt: a["org.opencontainers.image.created"] ?? "",
    imageRef: savedImageRef(user, id),
    ...(manifest.layers?.length &&
    manifest.layers.every(
      (layer) =>
        typeof layer.size === "number" &&
        Number.isFinite(layer.size) &&
        layer.size >= 0,
    )
      ? {
          sizeBytes: manifest.layers.reduce(
            (total, layer) => total + layer.size!,
            0,
          ),
        }
      : {}),
  };
}

// All filesystem archives (including app credentials) are authenticated and encrypted.
// Files use: 8-byte version marker, 12-byte IV, ciphertext, 16-byte GCM tag.
const magic = Buffer.from("FHAPP001");
export async function encryptArchive(
  source: string,
  destination: string,
  key: Buffer,
) {
  const iv = randomBytes(12);
  const cipher = createCipheriv("aes-256-gcm", key, iv);
  const file = await open(destination, "w", 0o600);
  try {
    await file.write(Buffer.concat([magic, iv]));
    await pipeline(
      createReadStream(source),
      cipher,
      createWriteStream(destination, { flags: "a", mode: 0o600 }),
    );
    await file.write(
      cipher.getAuthTag(),
      0,
      16,
      (await stat(destination)).size,
    );
  } finally {
    await file.close();
  }
}
export async function decryptArchive(
  source: string,
  destination: string,
  key: Buffer,
) {
  const file = await open(source, "r");
  try {
    const size = (await file.stat()).size;
    if (size < 36) throw new Error("Invalid saved app archive.");
    const header = Buffer.alloc(20),
      tag = Buffer.alloc(16);
    await file.read(header, 0, 20, 0);
    await file.read(tag, 0, 16, size - 16);
    if (!header.subarray(0, 8).equals(magic))
      throw new Error("Invalid saved app archive version.");
    const decipher = createDecipheriv("aes-256-gcm", key, header.subarray(8));
    decipher.setAuthTag(tag);
    await pipeline(
      createReadStream(source, { start: 20, end: size - 17 }),
      decipher,
      createWriteStream(destination, { mode: 0o600 }),
    );
  } finally {
    await file.close();
  }
}

export async function fileDigest(path: string) {
  const hash = createHash("sha256");
  for await (const chunk of createReadStream(path)) hash.update(chunk);
  return `sha256:${hash.digest("hex")}`;
}

export function shellQuote(value: string) {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

export function registryImageReference(value: string) {
  // Fly stores tag@digest; OCI clients require digest references without the tag.
  return value.replace(/:[^/:]+(@sha256:)/, "$1");
}

// Export all regular on-disk content; kernel/boot files are regenerated by Fly.
// Mounted app volumes are archived separately because --one-file-system skips them.
// Pause app processes for a consistent copy and resume them even on export failure.
export function machineExportScript(
  directory: string,
  mounts: string[],
  loader?: string,
) {
  if (!/^\/tmp\/flyhub-export-[a-f0-9]{32}$/.test(directory))
    throw new Error("Invalid export directory.");
  for (const mount of mounts)
    if (
      !mount.startsWith("/") ||
      mount.split("/").includes("..") ||
      mount === "/"
    )
      throw new Error("Invalid volume mount.");
  if (loader && !/^ld-musl-[a-z0-9_]+\.so\.1$/.test(loader))
    throw new Error("Invalid export loader.");
  return `#!/bin/sh
set -eu
umask 077
directory=${shellQuote(directory)}
mkdir -p "$directory"
mkdir -p "$directory/boot/proc" "$directory/boot/sys" "$directory/boot/dev" "$directory/boot/run" "$directory/boot/.fly"
chmod 755 "$directory/boot/proc" "$directory/boot/sys" "$directory/boot/dev" "$directory/boot/run" "$directory/boot/.fly"
${loader ? `tar -xzf "$directory.tools.tgz" -C "$directory"\nexport_tar() { "$directory/tools/${loader}" --library-path "$directory/tools" "$directory/tools/tar" "$@"; }` : 'export_tar() { tar "$@"; }'}
ancestors=" 1 "
pid=$$
while [ "$pid" -gt 1 ]; do
  ancestors="$ancestors$pid "
  pid=$(awk '/^PPid:/ {print $2}' "/proc/$pid/status")
done
paused=""
resume() { for pid in $paused; do kill -CONT "$pid" 2>/dev/null || true; done; }
trap 'resume; [ -z "\${watchdog:-}" ] || kill "$watchdog" 2>/dev/null || true' EXIT
trap 'exit 130' HUP INT TERM
for entry in /proc/[0-9]*; do
  pid=\${entry##*/}
  case "$ancestors" in *" $pid "*) continue ;; esac
  name=$(cat "$entry/comm" 2>/dev/null || true)
  case "$name" in init|hallpass|sshd|systemd*|udevd|chronyd|"" ) continue ;; esac
  [ "$(wc -c < "$entry/cmdline" 2>/dev/null || echo 0)" -gt 0 ] || continue
  if kill -STOP "$pid" 2>/dev/null; then paused="$paused $pid"; fi
done
(sleep 900; resume; touch "$directory/timed-out") </dev/null >/dev/null 2>&1 &
watchdog=$!
export_tar -C / --one-file-system --numeric-owner --xattrs --acls --exclude='./proc' --exclude='./sys' --exclude='./dev' --exclude='./run' --exclude='./.fly' --exclude='./lib/modules' --exclude='./usr/lib/modules' --exclude=./${directory.slice(1)} --exclude=./${directory.slice(1)}.sh --exclude=./${directory.slice(1)}.tools.tgz -I 'gzip -1' -cf "$directory/root.tgz" . -C "$directory/boot" proc sys dev run .fly
${mounts
  .map((mount, index) => {
    const base = mount.replace(/\/+$/, "");
    const temporary = directory.startsWith(`${base}/`)
      ? `.${directory.slice(base.length)}`
      : null;
    const excludes = temporary
      ? [temporary, `${temporary}.sh`, `${temporary}.tools.tgz`]
          .map((path) => `--exclude=${shellQuote(path)}`)
          .join(" ")
      : "";
    return `export_tar -C ${shellQuote(mount)} --one-file-system --numeric-owner --xattrs --acls ${excludes} -I 'gzip -1' -cf "$directory/volume-${index}.tgz" .`;
  })
  .join("\n")}
[ ! -e "$directory/timed-out" ] || { echo "Snapshot copy exceeded 15 minutes" >&2; exit 1; }
`;
}
